name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Run non-network tests
        run: go test ./pkg/... -v
        env:
          RUN_NETWORK_TESTS: "false"
        # 这是必须成功的主要测试

      - name: Run repository tests with network (ParseIndexPage)
        run: go test ./pkg/repository -v -run "TestPypiRepository_ParseIndexPage"
        env:
          RUN_NETWORK_TESTS: "true"
        continue-on-error: true
        # 允许这个测试失败，因为它依赖网络

      - name: Run repository basic tests
        run: go test ./pkg/repository -v -run "TestNewRepository"
        env:
          RUN_NETWORK_TESTS: "true"
        # 基本仓库测试应该能通过

      - name: Run repository package tests (might be unstable)
        run: go test ./pkg/repository -v -run "TestPypiRepository_GetPackage"
        env:
          RUN_NETWORK_TESTS: "true"
        continue-on-error: true
        # 允许这个测试失败，因为它依赖外部API

      - name: Run model tests with network (might be unstable)
        run: go test ./pkg/model -v -run "TestReleaseURL_Download"
        env:
          RUN_NETWORK_TESTS: "true"
        continue-on-error: true
        # 允许这个测试失败，因为它依赖网络 